image: node:14

cache:
  paths:
    - node_modules/

test:
  script:
    - yarn policies set-version v1
    - yarn --frozen-lockfile
    - yarn build
    - yarn lint
    - yarn test

release:
  when: manual
  before_script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git config user.name "Social Groovy Bot"
    - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
  script:
    - yarn policies set-version v1
    - yarn --frozen-lockfile
    - yarn build
    - npx semantic-release
