name: main
on:
  - push
  - pull_request


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn

      - name: Installing
        run: yarn --frozen-lockfile --perfer-offline --link-duplicates

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test --coverage --coverageReporters=lcov --coverageReporters=text-summary

      - name: Send test coverage to codecov
        continue-on-error: true
        uses: codecov/codecov-action@v2

      - name: Build
        run: yarn build --outDir lib

      - name: Archive lib
        uses: actions/upload-artifact@v3
        with:
          name: lib
          path: lib/

      # - name: Functional tests
      #   run: yarn e2e

  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download lib form build job
        uses: actions/download-artifact@v2
        with:
          name: lib
          path: lib/

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}
  
